apiVersion: v1
kind: Pod
metadata:
 name: my-liveness-readiness-pod
spec:
 containers:
 - name: my-app-container
   image: nginx
   livenessProbe:
    exec:
     command:
     - echo
     - testing
    initialDelaySeconds: 5
    periodSeconds: 5
   readinessProbe:
    httpGet:
     path: /
     port: 80
    initialDelaySeconds: 5
    periodSeconds: 5
   
