apiVersion: v1
kind: Pod
metadata:
 name: my-secret-pod
spec:
 containers:
 - name: my-app-container
   image: busybox
   command: ['sh', '-c', "echo Hello, World! && sleep 3600"]
   env:
   - name: MY_PASSWORD
     valueFrom:
      secretKeyRef:
       name: my-secret
       key: myKey
