apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-web-servers-deployment
spec:
 replicas: 3
 selector:
  matchLabels:
   name: nginx-web-servers
   environment: development
 template:
   metadata:
    labels: 
     name: nginx-web-servers
     environment: development
   spec:
    containers:
    - name: nginx
      image: nginx:1.7.9
      ports:
      - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
 name: nginx-service
spec:
 type: ClusterIP
 selector:
  name: nginx-web-servers
 ports:
 - protocol: TCP
   port: 8080
   targetPort: 80
